services:
  postgres:
    image: postgres:17-alpine
    command: ["-c", "wal_level=logical", "-c", "max_wal_senders=10", "-c", "max_replication_slots=10"]
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: meower
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", 'pg_isready -U user -d meower']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrate:
    image: migrate/migrate
    volumes:
      - ./../../migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgresql://user:password@postgres:5432/meower?sslmode=disable", "up"]
    links: 
      - postgres
    depends_on:
      postgres:
        condition: service_healthy

  memcached:
    image: memcached:1.6-alpine
    container_name: memcached
    restart: unless-stopped
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
    ports:
      - 11211:11211

  kafka:
    image: docker.io/bitnami/kafka:3.9
    ports:
      - '9094:9094'
    restart: unless-stopped
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER

  panda-console:
    image: redpandadata/console
    container_name: panda-console
    ports:
      - 3004:8080
    environment:
      KAFKA_BROKERS: kafka:9092

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/dev-prom.yaml'
    ports:
       - 9090:9090
    restart: unless-stopped
    volumes:
      - ./../metric/dev:/etc/prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.60
    container_name: jaeger
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    hostname: jaeger
    ports:
      - 16686:16686
    #   - 4317:4317
    #   - 4318:4318
    #   - 14268:14268
    restart: unless-stopped

  user-service:
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_started
      kafka:
        condition: service_started
      jaeger:
        condition: service_started
      prometheus:
        condition: service_started
    image: ${IMAGE_SERVICE}
    container_name: user-service
    environment:
      OTLP_PROBABILITY: 1
      OTEL_EXPORTER_OTLP_ENDPOINT: http://jaeger:4318
      OTEL_EXPORTER_OTLP_INSECURE: true
      LOG_LEVEL: debug
      PG_URI: postgresql://user:password@postgres:5432/meower?sslmode=disable
      MEMCACHED_ADDRESSES: memcached:11211
      KAFKA_BROKERS: kafka:9092
    ports:
       - 3001:3001
    #   - 3002:3002
    restart: unless-stopped

  user-outbox:
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_started
      prometheus:
        condition: service_started
    image: ${IMAGE_OUTBOX}
    container_name: user-outbox
    environment:
      LOG_LEVEL: info
      PG_URI: postgresql://user:password@postgres:5432/meower?sslmode=disable
      KAFKA_BROKERS: kafka:9092
      METRIC_PORT: 3002
    restart: unless-stopped